# Generated by Django 4.0.5 on 2022-06-21 00:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=functions.models.manga_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('AC', 'Ação'), ('AV', 'Aventura'), ('IS', 'Isekai'), ('FT', 'Fantansia'), ('HT', 'Hentai'), ('EC', 'Ecchi'), ('CT', 'Cultivação')], max_length=20)),
                ('descricao', models.TextField(max_length=500)),
                ('capa', models.ImageField(upload_to=functions.models.manga_directory_path)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NewCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_number', models.PositiveIntegerField()),
                ('images', models.ManyToManyField(to='functions.images')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.manga')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.manga'),
        ),
    ]
