# Generated by Django 4.0.5 on 2022-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_manga_favoritos_manga_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='cap_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
