# Generated by Django 4.0.5 on 2022-06-21 12:57

from django.db import migrations, models
import functions.models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_images_cap_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=functions.models.banner_directory_path),
        ),
        migrations.AlterField(
            model_name='manga',
            name='capa',
            field=models.ImageField(upload_to=functions.models.banner_directory_path),
        ),
    ]
