# Generated by Django 4.0.5 on 2022-06-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcap',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
