# Generated by Django 4.0.5 on 2022-06-22 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0007_newcap_update_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='profile',
            name='favoritos',
            field=models.ManyToManyField(blank=True, null=True, related_name='favoritados', to=settings.AUTH_USER_MODEL),
        ),
    ]
