# Generated by Django 4.0.5 on 2022-06-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0013_remove_manga_capitulos_manga_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='teste',
        ),
        migrations.AddField(
            model_name='manga',
            name='teste',
            field=models.ManyToManyField(related_name='testezin', to='functions.newcap'),
        ),
    ]
