# Generated by Django 4.0.5 on 2022-06-25 14:22

from django.db import migrations, models
import functions.models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0014_remove_manga_teste_manga_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=functions.models.user_picture_directory),
        ),
    ]
