# Generated by Django 4.0.5 on 2022-06-25 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0016_profile_profile_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_banner',
        ),
        migrations.AddField(
            model_name='profile',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seguidores',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
