# Generated by Django 4.0.5 on 2022-06-25 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0017_remove_profile_profile_banner_profile_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcap',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
